import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import AuthContext from "@/context/AuthContext";
import "./globals.css";
// import Navbar from "./components/Navbar";

const notoSansKr = Noto_Sans_KR({
    weight: ["500"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="kr" className={notoSansKr.className}>
            {/* w-full max-w-screen-xl overflow-auto mx-auto */}
            <body className="w-full h-full overflow-auto mx-auto">
                <AuthContext>
                    <header className="sticky top-0 bg-white z-10 border-b">
                        {/* <Navbar /> */}
                    </header>

                    <main className="bg-slate-400">{children}</main>
                </AuthContext>
            </body>
        </html>
    );
}
